apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{app_Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{app_Name}}
  template:
    metadata:
      labels:
        app: {{app_Name}}
    spec:
      imagePullSecrets:
      - name: dockercred
      containers:
      - name: {{app_Name}}
        image: {{image_name}}:{{version}}
        ports:
          - name: http-port
            containerPort: 8080
